apiVersion: batch/v1
kind: CronJob
metadata:
  name: article-crawling-server
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: crawling
              env:
                - name: PROFILE
                  value: "prod"
              image: sksjsksh32/article-crawling-server:555aa3cc371b9f84a3f5acbec9598a2319012cc8
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
