apiVersion: batch/v1
kind: CronJob
metadata:
  name: article-crawling-server
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: crawling
              env:
                - name: PROFILE
                  value: "prod"
              image: sksjsksh32/article-crawling-server:93dceb0003847acf3feac06c73f85ec6cc298759
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
