spring:
  application:
    name: k8s-java-consumer
  kafka:
    consumer:
      bootstrap-servers: host.docker.internal:29092
      group-id: group_prod
  data:
    mongodb:
      uri: mongodb://admin:password123@host.docker.internal:31200/k8s?authSource=admin