spring:
  application:
    name: k8s-java-consumer
  kafka:
    consumer:
      bootstrap-servers: localhost:19092
      group-id: group_1
  data:
    mongodb:
      uri: mongodb://admin:password123@localhost:31200/k8s?authSource=admin

