apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongodb-init-replica.sh: |
    #!/bin/bash
    mongosh admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD <<EOF
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "mongodb-0.mongodb-service.default.svc.cluster.local:27017" },
        { _id: 1, host: "mongodb-1.mongodb-service.default.svc.cluster.local:27017" }
      ]
    });
    EOF