apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-was-server
  labels:
    app: article-was-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: article-was-server
  template:
    metadata:
      name: article-was-server
      labels:
        app: article-was-server
    spec:
      containers:
        - name: article-was-server
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: sksjsksh32/article-was-server:4f85fe830d938ef3f7039da9f5ff653efac60a52
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: article-was-server
spec:
  ports:
    - name: article-was-svc
      port: 8080
      targetPort: 8080
      nodePort: 31100
  selector:
    app: article-was-server
  type: NodePort