spring:
  application:
    name: article-refine-server
  kafka:
    consumer:
      bootstrap-servers: 192.168.45.192:29092
      group-id: group_prod
    producer:
      bootstrap-servers: 192.168.45.192:29092
  data:
    mongodb:
      uri: mongodb://admin:password123@mongodb-service:31200/k8s?authSource=admin

custom:
  data:
    mongodb:
      collection: article
  kafka:
    consumer:
      topic: raw-article
    producer:
      topic: refine-article
    dlq:
      topic: raw-article-dlq