spring:
  application:
    name: javaserver
  kafka:
    streams:
      bootstrap-servers: host.docker.internal:29092
      application-id: web-stomp
      topic-name: refine-article
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
