spring:
  application:
    name: article-realtime-publish-server
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: web-stomp-dev
      topic-name: refine-article-dev

server:
  port: 8081
