apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawling
spec:
  schedule: "0/10 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: crawling
              env:
                - name: PROFILE
                  value: "prod"
              image: sksjsksh32/k8s-crawling:09de9b8140e9371ebc4bec1b6bcc3c185250ed3c
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
