# two node (one workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 31000
        hostPort: 31000
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
  - role: worker
    extraPortMappings:
      - containerPort: 31100
        hostPort: 31100
        listenAddress: "0.0.0.0"
        protocol: tcp
  - role: worker
    extraPortMappings:
      - containerPort: 31200
        hostPort: 31200
        listenAddress: "0.0.0.0"
        protocol: tcp