apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawling
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: crawling
              env:
                - name: PROFILE
                  value: "prod"
              image: sksjsksh32/k8s-crawling:ad8f7efbfa3853b907db933310d66bb562d953e2
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
