apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawling
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: crawling
              env:
                - name: PROFILE
                  value: "prod"
              image: sksjsksh32/k8s-crawling:2438a8dede505a675fb6558b2461fc313423930d
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
