apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-refine-server
  labels:
    app: article-refine-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-refine-server
  template:
    metadata:
      name: article-refine-server
      labels:
        app: article-refine-server
    spec:
      containers:
        - name: article-refine-server
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          image: sksjsksh32/article-refine-server:e5b171c08bd3cf581f1a43bc2793cf0ce204db2b
          imagePullPolicy: IfNotPresent
      restartPolicy: Always