apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      name: java-app
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: sksjsksh32/k8s-javaserver:e5b171c08bd3cf581f1a43bc2793cf0ce204db2b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  ports:
    - name: java-app-svc
      port: 8080
      targetPort: 8080
      nodePort: 31100
  selector:
    app: java-app
  type: NodePort