apiVersion: batch/v1
kind: CronJob
metadata:
  name: article-daily-batch-server
spec:
  schedule: "0/3 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
            - name: daily-batch-server
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "prod"
                - name: SENDER_SLACK_URL
                  valueFrom:
                    secretKeyRef:
                      name: article-batch-secrets
                      key: slack-url
              image: sksjsksh32/article-daily-batch-server:912f53616b308d6a4c19bbba0affb7c7788e0eaf
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
