spring:
  application:
    name: article-realtime-publish-server
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
      topic-name: realtime-article-dev
    streams:
      bootstrap-servers: localhost:9092
      application-id: web-stomp-dev
      topic-name: refine-article-dev

custom:
  stomp:
    url: localhost
    port: 8080

server:
  port: 8081
