spring:
  application:
    name: article-realtime-publish-server
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: host.docker.internal:29092
      topic-name: realtime-article
    streams:
      bootstrap-servers: host.docker.internal:29092
      application-id: web-stomp
      topic-name: refine-article

custom:
  stomp:
    url: article-was-server
    port: 8080

server:
  port: 8081