spring:
  application:
    name: article-realtime-publish-server
  kafka:
    streams:
      bootstrap-servers: host.docker.internal:29092
      application-id: web-stomp
      topic-name: refine-article

custom:
  stomp:
    url: java-app
    port: 8080

server:
  port: 8081