spring:
  application:
    name: article-realtime-publish-server
  kafka:
    streams:
      bootstrap-servers: host.docker.internal:29092
      application-id: web-stomp
      topic-name: refine-article

server:
  port: 8081