apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-realtime-publish-server
  labels:
    app: article-realtime-publish-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-realtime-publish-server
  template:
    metadata:
      name: article-realtime-publish-server
      labels:
        app: article-realtime-publish-server
    spec:
      containers:
        - name: article-realtime-publish-server
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          image: sksjsksh32/article-realtime-publish-server:4f85fe830d938ef3f7039da9f5ff653efac60a52
          imagePullPolicy: IfNotPresent
      restartPolicy: Always