spring:
  application:
    name: article-daily-batch-server
  data:
    mongodb:
      uri: mongodb://admin:password123@localhost:31200/k8s?authSource=admin
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql



custom:
  data:
    mongodb:
      article-collection: article
      article-rank-collection: article-rank