apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-consumer
  labels:
    app: java-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-consumer
  template:
    metadata:
      name: java-consumer
      labels:
        app: java-consumer
    spec:
      containers:
        - name: java-consumer
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          image: sksjsksh32/k8s-java-consumer:d9f202beedff2c01af592f2428ba32b344a766f0
          imagePullPolicy: IfNotPresent
      restartPolicy: Always