name: Docker Image CI - java-consumer

on:
  push:
    branches: [ "main" ]
    paths:
      - 'k8s-java-consumer/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'k8s-java-consumer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}  # 커밋 해시를 태그로 사용
    steps:
      # 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Docker 빌드 및 푸시
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./k8s-java-consumer
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-java-consumer:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-java-consumer:${{ env.TAG }}